---
- name: Install and configure NGINX on RHEL 9
  hosts: all
  become: yes  # Run tasks with root privileges

  tasks:
    - name: Ensure packages are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - firewalld

    - name: Ensure NGINX service is running and enabled
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Open HTTP (port 80) in firewalld
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
      notify: Reload firewalld

    - name: Open HTTPS (port 443) in firewalld
      ansible.posix.firewalld:
        service: https
        permanent: yes
        state: enabled
      notify: Reload firewalld

  handlers:
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
